kumuluzee:
  name: rso-airline-weather
  version: 1.1.0
  env:
    name: dev
    darksky: ${DARKSKY}
  server:
    base-url: http://localhost:8083
    http:
      port: 8083
  datasources:
  - jndi-name: jdbc/fri_airline
    connection-url: lala
    username: postgres
    password: pass
    max-pool-size: 20
  config:
    etcd:
      hosts: http://192.168.99.100:2379
  discovery:
    etcd:
      hosts: http://192.168.99.100:2379
    ttl: 30
    ping-interval: 5