apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather
  template:
    metadata:
      labels:
        app: weather
    spec:
      containers:
      - image: rsoairlines/fri-airlines-weather:0.0.4
        name: weather
        env:
        - name: DARKSKY
          valueFrom:
            secretKeyRef:
              name: ds-key
              key: ds-key
        - name: KUMULUZEE_DISCOVERY_CLUSTER
          value: gcloud
        - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
          value: http://etcd:2379
        - name: KUMULUZEE_CONFIG_ETCD_HOSTS
          value: http://etcd:2379
        ports:
        - containerPort: 8083
          name: server
          protocol: TCP
